// Mocks generated by Mockito 5.4.6 from annotations
// in social_mate/test/features/home/services/home_services_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i2;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:social_mate/core/services/supabase_database_services.dart'
    as _i3;
import 'package:supabase_flutter/supabase_flutter.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFuture_0<T1> extends _i1.SmartFake implements _i2.Future<T1> {
  _FakeFuture_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SupabaseDatabaseServices].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseDatabaseServices extends _i1.Mock
    implements _i3.SupabaseDatabaseServices {
  MockSupabaseDatabaseServices() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Future<void> insertRow({
    required String? table,
    required Map<String, dynamic>? values,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertRow, [], {#table: table, #values: values}),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<Map<String, dynamic>> insertRowWithReturn({
    required String? table,
    required Map<String, dynamic>? values,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#insertRowWithReturn, [], {
              #table: table,
              #values: values,
            }),
            returnValue: _i2.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i2.Future<Map<String, dynamic>>);

  @override
  _i2.Future<int> countRows({
    required String? table,
    required _i4.PostgrestFilterBuilder<dynamic> Function(
      _i4.PostgrestFilterBuilder<dynamic>,
    )?
    filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#countRows, [], {#table: table, #filter: filter}),
            returnValue: _i2.Future<int>.value(0),
          )
          as _i2.Future<int>);

  @override
  _i2.Future<void> updateRow({
    required String? table,
    required Map<String, dynamic>? values,
    required String? column,
    required dynamic value,
    _i4.PostgrestFilterBuilder<dynamic> Function(
      _i4.PostgrestFilterBuilder<dynamic>,
    )?
    filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRow, [], {
              #table: table,
              #values: values,
              #column: column,
              #value: value,
              #filter: filter,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> updateRows({
    required String? table,
    required Map<String, dynamic>? values,
    required _i4.PostgrestFilterBuilder<dynamic> Function(
      _i4.PostgrestFilterBuilder<dynamic>,
    )?
    filter,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRows, [], {
              #table: table,
              #values: values,
              #filter: filter,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> upsertRow({
    required String? table,
    required Map<String, dynamic>? values,
    String? onConflict,
    bool? ignoreDuplicates = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#upsertRow, [], {
              #table: table,
              #values: values,
              #onConflict: onConflict,
              #ignoreDuplicates: ignoreDuplicates,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> updateRowIfExists({
    required String? table,
    required String? column,
    required dynamic value,
    required Map<String, dynamic>? values,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateRowIfExists, [], {
              #table: table,
              #column: column,
              #value: value,
              #values: values,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Future<void> deleteRow({
    required String? table,
    required String? column,
    required dynamic value,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteRow, [], {
              #table: table,
              #column: column,
              #value: value,
            }),
            returnValue: _i2.Future<void>.value(),
            returnValueForMissingStub: _i2.Future<void>.value(),
          )
          as _i2.Future<void>);

  @override
  _i2.Stream<List<T>> tableStream<T>({
    required String? table,
    required List<String>? primaryKey,
    required T Function(Map<String, dynamic>, String)? builder,
    _i4.SupabaseStreamFilterBuilder Function(_i4.SupabaseStreamFilterBuilder)?
    filter,
    int Function(T, T)? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#tableStream, [], {
              #table: table,
              #primaryKey: primaryKey,
              #builder: builder,
              #filter: filter,
              #sort: sort,
            }),
            returnValue: _i2.Stream<List<T>>.empty(),
          )
          as _i2.Stream<List<T>>);

  @override
  _i2.Stream<T> recordStream<T>({
    required String? table,
    required String? primaryKey,
    required String? id,
    required T Function(Map<String, dynamic>, String)? builder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordStream, [], {
              #table: table,
              #primaryKey: primaryKey,
              #id: id,
              #builder: builder,
            }),
            returnValue: _i2.Stream<T>.empty(),
          )
          as _i2.Stream<T>);

  @override
  _i2.Future<T> fetchRow<T>({
    required String? table,
    required String? primaryKey,
    required String? id,
    required T Function(Map<String, dynamic>, String)? builder,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRow, [], {
              #table: table,
              #primaryKey: primaryKey,
              #id: id,
              #builder: builder,
            }),
            returnValue:
                _i5.ifNotNull(
                  _i5.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#fetchRow, [], {
                      #table: table,
                      #primaryKey: primaryKey,
                      #id: id,
                      #builder: builder,
                    }),
                  ),
                  (T v) => _i2.Future<T>.value(v),
                ) ??
                _FakeFuture_0<T>(
                  this,
                  Invocation.method(#fetchRow, [], {
                    #table: table,
                    #primaryKey: primaryKey,
                    #id: id,
                    #builder: builder,
                  }),
                ),
          )
          as _i2.Future<T>);

  @override
  _i2.Future<List<T>> fetchRows<T>({
    required String? table,
    required T Function(Map<String, dynamic>, String)? builder,
    String? primaryKey,
    _i4.PostgrestFilterBuilder<dynamic> Function(
      _i4.PostgrestFilterBuilder<dynamic>,
    )?
    filter,
    int Function(T, T)? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRows, [], {
              #table: table,
              #builder: builder,
              #primaryKey: primaryKey,
              #filter: filter,
              #sort: sort,
            }),
            returnValue: _i2.Future<List<T>>.value(<T>[]),
          )
          as _i2.Future<List<T>>);

  @override
  _i2.Future<List<T>> fetchRowsWithTransform<T>({
    required String? table,
    required T Function(Map<String, dynamic>, String)? builder,
    String? primaryKey,
    _i4.PostgrestFilterBuilder<dynamic> Function(
      _i4.PostgrestFilterBuilder<dynamic>,
    )?
    filter,
    _i4.PostgrestTransformBuilder<dynamic> Function(
      _i4.PostgrestFilterBuilder<dynamic>,
    )?
    transform,
    int Function(T, T)? sort,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchRowsWithTransform, [], {
              #table: table,
              #builder: builder,
              #primaryKey: primaryKey,
              #filter: filter,
              #transform: transform,
              #sort: sort,
            }),
            returnValue: _i2.Future<List<T>>.value(<T>[]),
          )
          as _i2.Future<List<T>>);
}
